CREATE TABLE USUÁRIO 
( 
 ID INT PRIMARY KEY AUTO_INCREMENT,  
 nome VARCHAR(n) NOT NULL,  
 email VARCHAR(n) NOT NULL,  
 senha VARCHAR(n) NOT NULL,  
 tipo_acesso INT,  
 UNIQUE (email)
); 

CREATE TABLE CATEGORIA 
( 
 ID INT PRIMARY KEY AUTO_INCREMENT,  
 NOME VARCHAR(n) NOT NULL,  
 DESCRICAO VARCHAR(n) NOT NULL,  
 STATUS CHAR(n) NOT NULL,  
); 

CREATE TABLE CONSUMO 
( 
 ID INT PRIMARY KEY AUTO_INCREMENT,  
 QUANTIDADE INT NOT NULL,  
 DATA_CONSUMO DATE NOT NULL,  
); 

CREATE TABLE ALIMENTO 
( 
 ID INT PRIMARY KEY AUTO_INCREMENT,  
 NOME VARCHAR(n) NOT NULL,  
 QUANTIDADE INT NOT NULL,  
 UNIDADE_MED CHAR(n),  
 DATA_VALIDADE INT NOT NULL,  
); 

CREATE TABLE D 
( 
); 

